PREFIX = "!"
OWNER_IDS = []
DATABASE_NAME = ''
DATABASE_USERNAME = ''
DATABASE_PASSWORD = ''
DATABASE_HOST = ''
NO_PERMS = "You don't have permission to use this command."
TOKEN = ''
DEFAULT_DELAY = 30
CLIENT_ID = 
DROP_LOCATIONS = []
CURRENCY_EMOJI = "<:gold_coin:973071732858585088>"

# SOCIAL GIFS
FUCK_GIFS = []
LICK_GIFS = []
KISS_GIFS = []
KICK_GIFS = []
SPANK_GIFS = []
HUG_GIFS = []
SLAP_GIFS = []
RESTRAIN_GIFS = []
CUDDLE_GIFS = []
PET_GIFS = []
PUNCH_GIFS = []